name: ramadhan_ogp
description: "Ramadhan Orchid Green Park Apps"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  csv: ^6.0.0
  cupertino_icons: ^1.0.6
  date_format: ^2.0.7
  dio: ^5.4.1
  dropdown_search: ^5.0.6
  firebase_core: ^2.27.1
  firebase_storage: ^11.6.10
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_launcher_icons: ^0.13.1
  flutter_markdown: ^0.6.21
  flutter_screenutil: ^5.9.0
  form_validator: ^2.1.1
  fpdart: ^1.1.0
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  go_router: ^13.2.0
  google_fonts: ^6.2.0
  hooks_riverpod: ^2.4.10
  image_picker: ^1.0.7
  image_picker_web: ^3.1.1
  intl: ^0.19.0
  objectbox: ^2.5.1
  objectbox_flutter_libs: any
  riverpod_annotation: ^2.3.4
  skeletons: ^0.0.3
  supabase_flutter: ^2.3.4
  url_launcher: ^6.2.5
  uuid: ^4.3.3

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  objectbox_generator: any
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/ramadhan_kareem.png"
  image_path_android: "assets/images/ramadhan_kareem.png"
  image_path_ios: "assets/images/ramadhan_kareem.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  ios: false
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  web:
    generate: true
    image_path: "assets/images/ramadhan_kareem.png"
    background_color: "#FFFFFF"
    theme_color: "#ff6600"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/no_image.jpg
  fonts:
    - family: Arabic
      fonts:
        - asset: assets/fonts/Simplified Arabic Regular.ttf
        # - asset: fonts/Schyler-Italic.ttf
        #   style: italic
    - family: Taha Naskh
      fonts:
        - asset: assets/fonts/KFGQPC Uthman Taha Naskh Regular.ttf
