// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDULk7ZS7D-olznIPrErls0ppXklSiOoGs',
    appId: '1:916988200402:web:6e6e5d9fa1bea7b750740b',
    messagingSenderId: '916988200402',
    projectId: 'ramadhan-ogp',
    authDomain: 'ramadhan-ogp.firebaseapp.com',
    storageBucket: 'ramadhan-ogp.appspot.com',
    measurementId: 'G-R0P6X7BM35',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdddm037CWlTdOuUj5rXwwPW5hfXtgtkI',
    appId: '1:916988200402:android:ebaa3bda135a1cda50740b',
    messagingSenderId: '916988200402',
    projectId: 'ramadhan-ogp',
    storageBucket: 'ramadhan-ogp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI8K_gPBz-WxNk6gFnLCjPlpekYclj6Os',
    appId: '1:916988200402:ios:fee65cfe74e59bab50740b',
    messagingSenderId: '916988200402',
    projectId: 'ramadhan-ogp',
    storageBucket: 'ramadhan-ogp.appspot.com',
    iosBundleId: 'com.example.ramahdanOgp',
  );
}
